name: Deploy Infrastructure and App

on:
  push:
    branches:
      - main # الـ Pipeline هيشتغل أول ما تعمل push لفرع main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
   
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

  
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
        
   
    - name: Terraform Init & Apply
      env:
        ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
        ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
        ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }} 
      run: |
        cd terraform
        terraform init
        terraform apply --auto-approve

  
    - name: Run Ansible Playbooks
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'
      run: |
        cd ansible
        sudo apt-get update && sudo apt-get install -y sshpass
        
        
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        
        ansible-playbook -i inventory.ini web.yml --private-key=private_key.pem
        ansible-playbook -i inventory.ini haproxy.yml --private-key=private_key.pem
